WIP: Add EvaluateEntitlement filter
rciam/simplesamlphp-module-entitlement pull request #1
Opened 2021-01-20 17:42 UTC by nikosev

2021-01-22 08:58 UTC, NicolasLiampotis requested changes
- Rename filter to AddCapability
- Add debug log

2021-01-22 08:58 UTC, NicolasLiampotis commented on lib/Auth/Process/ΕvaluateΕntitlement.php
> +class sspmod_entitlement_Auth_Process_ΕvaluateΕntitlement extends SimpleSAML_Auth_ProcessingFilter
Rename `EvaluateEntitlement` to `AddCapability`

2021-01-22 08:58 UTC, NicolasLiampotis commented on lib/Auth/Process/ΕvaluateΕntitlement.php
> + * Attribute filter to evaluate entitlement for access to Services.
"Attribute filter for evaluating the resources capabilities of the authenticating user. 
A capability defines the resource or child-resource the user is allowed to access, optionally specifying certain actions the user is entitled to perform. Capabilities can be used to convey – in a compact form – authorisation information. Capability values are formatted as URNs following the syntax specified in in https://aarc-community.org/guidelines/aarc-g027"

2021-01-22 08:58 UTC, NicolasLiampotis commented on lib/Auth/Process/ΕvaluateΕntitlement.php
> +     * The attribute that will hold the entitlement value.
The attribute that will hold the capability value(s)

2021-01-22 08:58 UTC, NicolasLiampotis commented on lib/Auth/Process/ΕvaluateΕntitlement.php
> +     * The assigned entitlement value.
The assigned capability value(s)

2021-01-22 08:58 UTC, NicolasLiampotis commented on lib/Auth/Process/ΕvaluateΕntitlement.php
> +    private $entitlement = array();
`entitlement` --> `capability`

2021-01-22 08:58 UTC, NicolasLiampotis commented on lib/Auth/Process/ΕvaluateΕntitlement.php
> +     * List of IdP entity IDs excluded from this entitlement.
List of IdP entity IDs excluded from this capability

2021-01-22 08:58 UTC, NicolasLiampotis commented on lib/Auth/Process/ΕvaluateΕntitlement.php
> +     * List of IdP entity IDs qualifying for this entitlement.
List of IdP entity IDs qualifying for this capability

2021-01-22 08:58 UTC, NicolasLiampotis commented on lib/Auth/Process/ΕvaluateΕntitlement.php
> +     * Combination of entity attributes qualifying for this entitlement.
... qualifying for this entitlement --> qualifying for this capability

2021-01-22 08:58 UTC, NicolasLiampotis commented on lib/Auth/Process/ΕvaluateΕntitlement.php
> +     * List of user entitlements qualifying for this entitlement.
List of user entitlements qualifying for this capability

2021-01-22 08:58 UTC, NicolasLiampotis commented on lib/Auth/Process/ΕvaluateΕntitlement.php
> +                SimpleSAML_Logger::error("[ΕvaluateΕntitlement] Configuration error: 'attributeName' not a string literal");
[AddCapability]

2021-01-22 08:58 UTC, NicolasLiampotis commented on lib/Auth/Process/ΕvaluateΕntitlement.php
> +        if (array_key_exists('entitlement', $config)) {
entitlement --> capability

2021-01-22 08:58 UTC, NicolasLiampotis commented on lib/Auth/Process/ΕvaluateΕntitlement.php
> +        $state['Attributes'][$this->attributeName] = array_merge($state['Attributes'][$this->attributeName], $this->entitlement);
`$this->entitlement` --> `$this-->capability`

2021-01-22 08:58 UTC, NicolasLiampotis commented on lib/Auth/Process/ΕvaluateΕntitlement.php
> +        $state['Attributes'][$this->attributeName] = array_merge($state['Attributes'][$this->attributeName], $this->entitlement);
Add debug: `"[AddCapability] Adding capability " . var_export($this-->capability, true)"`

2021-01-22 10:47 UTC, nikosev commented
Change requests have been resolved

2021-03-01 09:08 UTC, NicolasLiampotis approved these changes
LGTM

2021-03-01 09:09 UTC, merged